# Generated by Django 2.0.2 on 2018-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0002_auto_20180222_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_group_images/'),
        ),
    ]
