# Generated by Django 2.0.2 on 2018-03-02 04:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0004_auto_20180222_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lower case alphabets are allowed.')])),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='festflow.SponsorGroup'),
        ),
    ]
