# Generated by Django 2.0.2 on 2018-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0005_auto_20180302_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizermember',
            name='club',
            field=models.CharField(choices=[('GLUG', "GNU Linux Users' Group"), ('MNTC', 'Maths And Tech Club'), ('SAE', 'SAE')], default='GLUG', max_length=5),
        ),
    ]
