# Generated by Django 2.0.2 on 2018-10-07 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0006_organizermember_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only lower case alphabets are allowed.')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/')),
            ],
        ),
    ]
