# Generated by Django 2.0.2 on 2018-10-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0009_event_logo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logo2',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
