# Generated by Django 2.0.2 on 2018-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0010_auto_20181010_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tiles',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
