# Generated by Django 2.0.2 on 2018-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festflow', '0012_event_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='pastorpresent',
            field=models.CharField(blank=True, default='past', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
